#!/usr/bin/env python3
"""
Custom formatter for YouTube dataset with Silero VAD + Whisper transcriptions.
Reads from manifest.csv generated by youtube_dataset_builder.py
"""

import csv
from pathlib import Path
from typing import List, Tuple


def youtube_vad(root_path: str, meta_file: str, **kwargs) -> List[Tuple[str, str, str]]:
    """
    Custom formatter for YouTube VAD dataset.
    
    Args:
        root_path: Dataset root directory
        meta_file: Path to manifest.csv relative to root_path or absolute
        
    Returns:
        List of [text, audio_path, speaker_name] tuples
    """
    root = Path(root_path)
    manifest_path = Path(meta_file) if Path(meta_file).is_absolute() else root / meta_file
    
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    
    items: List[Tuple[str, str, str]] = []
    
    with manifest_path.open('r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            text = row['text'].strip()
            if not text:
                continue
                
            # Use audio_path from manifest (WAV format for training)
            audio_rel_path = row['audio_path']
            audio_path = str(root / audio_rel_path)
            
            # Single speaker dataset
            speaker_name = "youtube_speaker"
            
            items.append((text, audio_path, speaker_name))
    
    return items


# Register the formatter
if __name__ == "__main__":
    # Test the formatter
    import sys
    if len(sys.argv) > 1:
        dataset_path = sys.argv[1]
        items = youtube_vad(dataset_path, "manifest.csv")
        print(f"Loaded {len(items)} samples")
        print("First 3 samples:")
        for text, audio, speaker in items[:3]:
            print(f"  Text: {text}")
            print(f"  Audio: {audio}")
            print(f"  Speaker: {speaker}")
            print()
