#!/usr/bin/env python3
"""
Custom formatter for YouTube dataset with Silero VAD + Whisper transcriptions.
Reads from manifest.csv generated by youtube_dataset_builder.py
"""

import csv
from pathlib import Path
from typing import Dict, List


def youtube_vad(root_path: str, meta_file: str, **kwargs) -> List[Dict[str, str]]:
    """
    Custom formatter for YouTube VAD dataset.
    
    Args:
        root_path: Dataset root directory
        meta_file: Path to manifest.csv relative to root_path or absolute
        
    Returns:
        List of dataset items in Coqui format:
        {"text", "audio_file", "speaker_name", "root_path"}
    """
    root = Path(root_path)
    manifest_path = Path(meta_file) if Path(meta_file).is_absolute() else root / meta_file
    
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    
    items: List[Dict[str, str]] = []
    
    with manifest_path.open('r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            text = row.get("text", "").strip()
            if not text:
                continue

            # Use audio_path from manifest (WAV format for training)
            audio_rel_path = row.get("audio_path", "").strip()
            if not audio_rel_path:
                continue

            audio_file_path = (root / audio_rel_path).resolve()
            if not audio_file_path.exists():
                continue

            # Single speaker dataset
            speaker_name = "youtube_speaker"

            items.append(
                {
                    "text": text,
                    "audio_file": str(audio_file_path),
                    "speaker_name": speaker_name,
                    "root_path": str(root.resolve()),
                }
            )
    
    return items


# Register the formatter
if __name__ == "__main__":
    # Test the formatter
    import sys
    if len(sys.argv) > 1:
        dataset_path = sys.argv[1]
        items = youtube_vad(dataset_path, "manifest.csv")
        print(f"Loaded {len(items)} samples")
        print("First 3 samples:")
        for item in items[:3]:
            print(f"  Text: {item['text']}")
            print(f"  Audio: {item['audio_file']}")
            print(f"  Speaker: {item['speaker_name']}")
            print()
